### ISSUE TITLE
Server Crash from exeding maximum server lock and i belive its from TerraForged-1.15.2-0.1.0-BETA-1

### ISSUE THREAD

**Issue by Domsmasher1** [TerraForged/TerraForged#212]
---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 6/27/20 6:27 AM
Description: Exception ticking world

java.lang.Error: Maximum lock count exceeded
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryWriteLock(ReentrantReadWriteLock.java:563) ~[?:1.8.0_222] {}
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.tryLock(ReentrantReadWriteLock.java:1031) ~[?:1.8.0_222] {}
	at com.terraforged.core.concurrent.pool.ObjectPool.get(ObjectPool.java:55) ~[?:?] {re:classloading}
	at com.terraforged.core.cell.Cell.pooled(Cell.java:135) ~[?:?] {re:classloading}
	at com.terraforged.world.heightmap.WorldLookup.getCell(WorldLookup.java:39) ~[?:?] {re:classloading}
	at com.terraforged.mod.biome.provider.TerraBiomeProvider.lookupPos(TerraBiomeProvider.java:69) ~[?:?] {re:classloading}
	at com.terraforged.mod.biome.provider.TerraBiomeProvider.func_225526_b_(TerraBiomeProvider.java:76) ~[?:?] {re:classloading}
	at net.minecraft.world.biome.BiomeContainer.<init>(SourceFile:87) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222656_a(ChunkSerializer.java:69) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:485) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_222] {}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:551) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:560) ~[?:?] {re:classloading}
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:278) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:719) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:708) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:693) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.concurrent.locks.ReentrantReadWriteLock$Sync.tryWriteLock(ReentrantReadWriteLock.java:563)
	at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.tryLock(ReentrantReadWriteLock.java:1031)
	at com.terraforged.core.concurrent.pool.ObjectPool.get(ObjectPool.java:55)
	at com.terraforged.core.cell.Cell.pooled(Cell.java:135)
	at com.terraforged.world.heightmap.WorldLookup.getCell(WorldLookup.java:39)
	at com.terraforged.mod.biome.provider.TerraBiomeProvider.lookupPos(TerraBiomeProvider.java:69)
	at com.terraforged.mod.biome.provider.TerraBiomeProvider.func_225526_b_(TerraBiomeProvider.java:76)
	at net.minecraft.world.biome.BiomeContainer.<init>(SourceFile:87)
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222656_a(ChunkSerializer.java:69)
	at net.minecraft.world.server.ChunkManager.lambda$func_223172_f$14(ChunkManager.java:485)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213166_h(SourceFile:551)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118)
	at net.minecraft.world.server.ServerChunkProvider$ChunkExecutor.func_213168_p(SourceFile:560)
	at net.minecraft.world.server.ServerChunkProvider.func_217234_d(SourceFile:278)
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:719)

-- Affected level --
Details:
	All players: 3 total; [ServerPlayerEntity['ggZimt'/3002, l='world', x=-4711.02, y=131.00, z=-2515.58], ServerPlayerEntity['DomSmasher'/448, l='world', x=-4679.43, y=134.02, z=-2532.07], ServerPlayerEntity['M1tht1c'/693, l='world', x=-4683.25, y=138.38, z=-2681.48]]
	Chunk stats: ServerChunkCache: 4040
	Level dimension: DimensionType{minecraft:overworld}
	Level name: world
	Level seed: 1673171044
	Level generator: ID 07 - terraforged, ver 0. Features enabled: true
	Level generator options: {rivers:{riverCount:13,tertiaryRivers:{fade:0.95f,maxBankHeight:4,minBankHeight:0,bedDepth:3,bankWidth:8,bedWidth:4},secondaryRiver:{fade:0.95f,maxBankHeight:6,minBankHeight:1,bedDepth:4,bankWidth:14,bedWidth:5},primaryRivers:{fade:0.95f,maxBankHeight:8,minBankHeight:2,bedDepth:5,bankWidth:20,bedWidth:8}},miscellaneous:{vanillaWaterFeatures:"false",strataDecorator:"true",naturalSnowDecorator:"true",smoothLayerDecorator:"true",mountainBiomeUsage:0.4f,erosionDecorator:"true",customBiomeFeatures:"true"},structures:{strongholds:{distance:20,separation:20},villages:{distance:48,separation:12},oceanMonuments:{distance:24,separation:12},mansions:{distance:80,separation:20},otherStructures:{distance:32,separation:8},shipwrecks:{distance:32,separation:16},oceanRuins:{distance:32,separation:16}},climate:{biomeShape:{biomeWarpStrength:80,biomeSize:250,macroNoiseSize:8,biomeWarpScale:150},temperature:{falloff:3,min:0.0f,max:0.98f,bias:0.05f,scale:7},moisture:{falloff:1,min:0.0f,max:1.0f,bias:0.0f,scale:6},biomeEdgeShape:{octaves:2,strength:14,scale:24,type:"SIMPLEX",lacunarity:2.65f,gain:0.5f}},filters:{erosion:{dropletVelocity:0.7f,dropletLifetime:25,erosionRate:0.5f,dropletVolume:0.7f,depositeRate:0.5f,iterations:15000},smoothing:{smoothingRadius:1.75f,smoothingRate:0.85f,iterations:1}},world:{continent:{continentMode:"MULTI",continentShape:"EUCLIDEAN",oceanScale:0.8f,continentScale:3000},transitionPoints:{coast:0.425f,beach:0.375f,shallowOcean:0.32f,inland:0.55f,deepOcean:0.1f},properties:{spawnType:"CONTINENT_CENTER",seaLevel:63,worldHeight:256}},terrain:{mountains:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:2.0f},steppe:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:3.0f},badlands:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:2.0f},general:{globalVerticalScale:0.98f,globalHorizontalScale:1.0f,terrainRegionSize:1200},dales:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:2.0f},plains:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:3.0f},hills:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:2.0f},plateau:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:2.0f},torridonian:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:1.0f},volcano:{baseScale:1.0f,verticalScale:1.0f,horizontalScale:1.0f,weight:1.5f}},dimensions:{bedrockLayer:{minDepth:1,material:"minecraft:bedrock",variance:4},dimensions:{nether:"default",end:"default"}}}
	Level spawn location: World: (-4918,75,-2228), Chunk: (at 10,4,12 in -308,-140; contains blocks -4928,0,-2240 to -4913,255,-2225), Region: (-10,-5; contains chunks -320,-160 to -289,-129, blocks -5120,0,-2560 to -4609,255,-2049)
	Level time: 76587 game time, 57932 day time
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 77053 (now: false), thunder time: 88779 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:330)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:784)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:637)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Linux (amd64) version 4.14.158-129.185.amzn2.x86_64
	Java Version: 1.8.0_222, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 444687784 bytes (424 MB) / 1978662912 bytes (1887 MB) up to 3728736256 bytes (3556 MB)
	CPUs: 2
	JVM Flags: 2 total; -Xmx4000M -Xms200M
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.15.2-31.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.0
	FML Language Providers: 
		javafml@31.2
		minecraft@1
	Mod List: 
		forge-1.15.2-31.2.0-server.jar Minecraft {minecraft@1.15.2 DONE}
		forge-1.15.2-31.2.0-universal.jar Forge {forge@31.2.0 DONE}
		create-mc1.15.2_v0.2.4d.jar Create {create@mc1.15.2_v0.2.4d DONE}
		TerraForged-1.15.2-0.1.0-BETA-1.jar TerraForged {terraforged@0.1.0-BETA-1 DONE}
		journeymap-1.15.2-5.7.0beta1.jar Journeymap {journeymap@1.15.2-5.7.0beta1 DONE}
		jei-1.15.2-6.0.2.12.jar Just Enough Items {jei@6.0.2.12 DONE}
	Player Count: 3 / 20; [ServerPlayerEntity['ggZimt'/3002, l='world', x=-4711.02, y=131.00, z=-2515.58], ServerPlayerEntity['DomSmasher'/448, l='world', x=-4679.43, y=134.02, z=-2532.07], ServerPlayerEntity['M1tht1c'/693, l='world', x=-4683.25, y=138.38, z=-2681.48]]
	Data Packs: mod:journeymap (incompatible), vanilla, mod:forge (incompatible), mod:create, mod:terraforged, mod:jei (incompatible)
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)

Is this terraforge or something else?

**Comment by dags-** [comment]
Thanks, I am aware. There will be a fix out later today.

Please read the release notes more carefully in future:
> 3. Do not open github issues for anything relating to the beta. Please use #beta-discussion on discord instead
