### ISSUE TITLE
Error saving FileConfig while loading mods

### ISSUE THREAD

**Issue by Spirolateral** [TerraForged/TerraForged#218]
**Description**
After upgrading from 0.0.14 to 0.1.0 beta 2, I encounter an error while loading mods: "TerraForged (terraforged) encountered an error during the common_setup event phase. Error while saving the FileConfig to config/terraforged/biome_weights.conf"

This prevents me from playing the game at all.

I've tested it with 0.1.0 beta 1 as well and I encounter the same error.

**How to reproduce**
- I'm using ATLauncher to switch between versions of TerraForged.
- I have the latest versions of AutoRegLib, Quark, Create, JourneyMap, JEI, and HWYLA.
- I had a functional instance with these mods and TerraForged 0.0.14; switching out the version of TerraForged is the only thing necessary to cause the error.

**Comment by dags-** [comment]
Please provide the full debug log showing the error.

Keep in mind that as per the release notes, existing 0.0.14 worlds will _not_ be compatible with the 0.1.0 version of the mod (although it shouldn't crash the game).

**Comment by Spirolateral** [comment]
Is this what you're looking for? I'm new to submitting bug reports. This is from the ATLauncher console and it looks like it's the part that's relevant.

[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-3/INFO]: Common setup
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-3/INFO]: Registered world type
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-2/INFO]: Loading Module Chain Linkage
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-3/INFO]: Creating default config: biome_weights
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-2/INFO]: Loading Module Chute
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-2/INFO]: Loading Module Color Slime
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-2/INFO]: Loading Module Dispensers Place Blocks
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-2/INFO]: Loading Module Ender Watcher
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-2/INFO]: Loading Module Endermites Form Shulkers
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-3/ERROR]: Exception caught during firing event: Error while saving the FileConfig to config/terraforged/biome_weights.conf
[03/7/2020 11:25:41 AM] 	Index: 1
[03/7/2020 11:25:41 AM] 	Listeners:
[03/7/2020 11:25:41 AM] 		0: NORMAL
[03/7/2020 11:25:41 AM] 		1: ASM: class com.terraforged.mod.TerraForgedMod setup(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
[03/7/2020 11:25:41 AM] com.electronwill.nightconfig.core.io.WritingException: Error while saving the FileConfig to config/terraforged/biome_weights.conf
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.failed(WriteAsyncFileConfig.java:166)
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:124)
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:88)
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.save(SimpleCommentedFileConfig.java:33)
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigManager.create(ConfigManager.java:84)
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigManager.lambda$static$1(ConfigManager.java:20)
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigRef.get(ConfigRef.java:27)
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigManager.init(ConfigManager.java:68)
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.TerraForgedMod.setup(TerraForgedMod.java:68)
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.eventbus.ASMEventHandler_10_TerraForgedMod_setup_FMLCommonSetupEvent.invoke(.dynamic)
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106)
[03/7/2020 11:25:41 AM] 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
[03/7/2020 11:25:41 AM] 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65)
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112)
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135)
[03/7/2020 11:25:41 AM] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[03/7/2020 11:25:41 AM] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[03/7/2020 11:25:41 AM] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[03/7/2020 11:25:41 AM] 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291)
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[03/7/2020 11:25:41 AM] Caused by: java.nio.file.NoSuchFileException: config/terraforged/biome_weights.conf
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixFileSystemProvider.newAsynchronousFileChannel(UnixFileSystemProvider.java:196)
[03/7/2020 11:25:41 AM] 	at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:248)
[03/7/2020 11:25:41 AM] 	at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:301)
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:121)
[03/7/2020 11:25:41 AM] 	... 24 more
[03/7/2020 11:25:41 AM] 
[03/7/2020 11:25:41 AM] [11:25:41] [modloading-worker-3/ERROR]: Caught exception during event FMLCommonSetupEvent dispatch for modid terraforged
[03/7/2020 11:25:41 AM] com.electronwill.nightconfig.core.io.WritingException: Error while saving the FileConfig to config/terraforged/biome_weights.conf
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig$WriteCompletedHandler.failed(WriteAsyncFileConfig.java:166) ~[core-3.6.2.jar:?]
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:124) ~[core-3.6.2.jar:?]
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:88) ~[core-3.6.2.jar:?]
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.SimpleCommentedFileConfig.save(SimpleCommentedFileConfig.java:33) ~[core-3.6.2.jar:?]
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigManager.create(ConfigManager.java:84) ~[?:?]
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigManager.lambda$static$1(ConfigManager.java:20) ~[?:?]
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigRef.get(ConfigRef.java:27) ~[?:?]
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.config.ConfigManager.init(ConfigManager.java:68) ~[?:?]
[03/7/2020 11:25:41 AM] 	at com.terraforged.mod.TerraForgedMod.setup(TerraForgedMod.java:68) ~[?:?]
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.eventbus.ASMEventHandler_10_TerraForgedMod_setup_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?]
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?]
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.fml.javafmlmod.FMLModContainer.fireEvent(FMLModContainer.java:106) ~[?:31.2]
[03/7/2020 11:25:41 AM] 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.function.Consumer.lambda$andThen$0(Consumer.java:65) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.fml.ModContainer.transitionState(ModContainer.java:112) ~[?:?]
[03/7/2020 11:25:41 AM] 	at net.minecraftforge.fml.ModList.lambda$null$10(ModList.java:135) ~[?:?]
[03/7/2020 11:25:41 AM] 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_251]
[03/7/2020 11:25:41 AM] Caused by: java.nio.file.NoSuchFileException: config/terraforged/biome_weights.conf
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at sun.nio.fs.UnixFileSystemProvider.newAsynchronousFileChannel(UnixFileSystemProvider.java:196) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:248) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at java.nio.channels.AsynchronousFileChannel.open(AsynchronousFileChannel.java:301) ~[?:1.8.0_251]
[03/7/2020 11:25:41 AM] 	at com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.save(WriteAsyncFileConfig.java:121) ~[core-3.6.2.jar:?]
[03/7/2020 11:25:41 AM] 	... 24 more

**Comment by dags-** [comment]
From the error it seems like the game directory is set up strangely. I'd need to see the entire log file to get an idea of how your custom launcher is setting things up (you can drag-drop into the github window to upload).

Are you able to reproduce the error in the official MC launcher?

**Comment by Spirolateral** [comment]
Um, I could try! I'd have to set everything up from scratch, though, 'cause ATLauncher uses a different directory.
Here's the entire log: https://paste.atlauncher.com/view/47410de4

**Comment by Spirolateral** [comment]
Update: I made a new ATLauncher instance with just TerraForged and no other mods, and I still got the error. So it looks like it's just TF and the launcher that aren't getting along. Also, the config/terraforged folder is showing up empty—perhaps it's trying to write to the folder in the default Minecraft directory? What's the file path it usually writes config files to? I can check there to see if that's where it ended up.

**Comment by dags-** [comment]
Have you tried with the official launcher?

**Comment by Spirolateral** [comment]
I haven't; as far as I know it isn't possible to move worlds from ATLauncher to the official launcher. (I also don't have Forge set up on the official launcher, so it would be a huge pain.) But since I haven't seen anyone else posting about this, I wouldn't imagine I'd encounter this bug on there.

**Comment by dags-** [comment]
Stick with 0.0.14 for now then. I'll make a note to test with the beta that the filepath works as intended on macos

**Comment by Spirolateral** [comment]
Will do; thanks!

**Comment by Spirolateral** [comment]
Hi! I was wondering if there were any updates on this. I made a brand new ATLauncher instance with just TerraForged 0.1.0 and no other mods, and I still got "TerraForged (terraforged) encountered an error during the common_setup event phase", this time without the note about biome_weights.conf (although that note is still included in my preexisting instance if I change the version to 0.1.0). As before, this makes the game completely unplayable.

Are there are any planned fixes? And could you tell me what directory TerraForged looks in for biome_weights.conf and what directory it tries to write it to?

**Comment by dags-** [comment]
There's one thing I can try to work around this launcher but I have no means to test as I won't be putting my login details into it. Will include the change in the next mod update but if it doesn't work I'd suggest you use a different launcher (the official one works fine on macos)

**Comment by Spirolateral** [comment]
Okay, many thanks!

**Comment by Spirolateral** [comment]
Update: I tried it out in GDLauncher and it works fine. So it looks like it's an issue between TerraForged and ATLauncher specifically rather than an issue with third-party launchers in general. Anyway, that means I now have a solution where I can still easily manage multiple instances and still get to use TerraForged! I'll be very excited to check out all the mod's new features in 0.1.0. Thanks for all your help!
