### ISSUE TITLE
Dont know what the problem is

### ISSUE THREAD

**Issue by James10898** [TerraForged/TerraForged#95]
Suddenly closes then gives me this crash report, dont know the problem though

---- Minecraft Crash Report ----

WARNING: coremods are present:
  CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
Contact their authors BEFORE contacting forge

// Why did you do that?

Time: 3/26/20 8:25 PM
Description: Exception in server tick loop

java.lang.NoSuchFieldError: waterLakeRarity
	at io.github.terra121.EarthTerrainProcessor.<init>(EarthTerrainProcessor.java:88)
	at io.github.terra121.EarthWorldType.createCubeGenerator(EarthWorldType.java:20)
	at net.minecraft.world.WorldProvider.createCubeGenerator(WorldProvider.java:759)
	at net.minecraft.world.WorldServer.initCubicWorldServer(WorldServer.java:1549)
	at io.github.opencubicchunks.cubicchunks.core.CommonEventHandler.onWorldAttachCapabilities(CommonEventHandler.java:121)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_CommonEventHandler_onWorldAttachCapabilities_AttachCapabilitiesEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:691)
	at net.minecraftforge.event.ForgeEventFactory.gatherCapabilities(ForgeEventFactory.java:679)
	at net.minecraft.world.World.initCapabilities(World.java:3973)
	at net.minecraft.world.WorldServer.func_175643_b(WorldServer.java:173)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:122)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 241728720 bytes (230 MB) / 637534208 bytes (608 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2824 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version                    | Source                                          | Signature                                |
	|:------ |:--------------- |:-------------------------- |:----------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2                     | minecraft.jar                                   | None                                     |
	| LCHIJA | mcp             | 9.42                       | minecraft.jar                                   | None                                     |
	| LCHIJA | FML             | 8.0.99.99                  | forge-1.12.2-14.23.5.2824.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2824               | forge-1.12.2-14.23.5.2824.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | cubicchunkscore | 1.12.2-0.0.1055.0-SNAPSHOT | minecraft.jar                                   | None                                     |
	| LCHIJA | cubicchunks     | 1.12.2-0.0.1055.0-SNAPSHOT | CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar  | None                                     |
	| LCHIJA | cubicgen        | 1.12.2-0.0.126.0-SNAPSHOT  | CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar | None                                     |
	| LCHIJA | terra121        | 0.1                        | terra121-0.1.jar                                | None                                     |

	Loaded coremods (and transformers): 
CubicChunksCoreMod (CubicChunks-1.12.2-0.0.1055.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.core.asm.transformer.CubicChunksWorldEditTransformer
CubicGenCoreMod (CubicWorldGen-1.12.2-0.0.126.0-SNAPSHOT-all.jar)
  io.github.opencubicchunks.cubicchunks.cubicgen.asm.coremod.MapGenStrongholdCubicConstructorTransform
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	CubicChunks WorldGen Hang Watchdog samples: (no data)
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by CreativeRealms** [comment]
This is the TerraForged Github not the Terra121 Github.
